const races = {
  0: 'Kreuzung',
  1: 'Holstein',
  100: 'Undefiniert',
  101: 'Pustertaler Sprinzen',
  102: 'Bordelaise',
  103: 'Low Line',
  104: 'Welsh Black',
  14: 'Hinterwaelder',
  2: 'Rotfleckvieh',
  21: 'Charolais',
  22: 'Limousin',
  23: 'Weissblaue Belgier',
  24: "Blonde d'Aquitaine",
  25: 'Maine Anjou',
  26: 'Salers',
  27: '"Montbéliard',
  28: 'Aubrac',
  29: 'Gasconne',
  3: 'Jersey',
  31: 'Piemonteser',
  32: 'Chianina',
  33: 'Romagnola',
  34: 'Marchigiana',
  35: 'INRA95',
  4: 'Braunvieh',
  42: 'Angus',
  43: 'Hereford',
  45: 'Highland Cattle',
  47: 'Galloway',
  48: 'Guernsey',
  49: 'Swiss Fleckvieh',
  5: 'Angler',
  50: 'Luing',
  51: 'Kiwicross',
  52: 'Normande',
  53: 'Ayrshire',
  54: 'Abondance',
  55: 'Grauvieh',
  56: 'Dexter',
  57: 'Bazadaise',
  58: 'Tuxer',
  59: 'Murnau Werdenfelser',
  6: 'Original Braunvieh',
  7: 'Red Holstein',
  71: 'Dänische Rotbunte',
  72: 'Schwedische Rotbunte',
  73: 'Norwegische Rotbunte',
  74: 'Pinzgauer',
  78: 'Simmental',
  80: 'Dahomey',
  81: 'Tarentaise',
  82: 'Vosgienne',
  83: 'Texas Longhorn',
  84: 'Gelbvieh',
  87: 'Wasserbüffel',
  88: 'Bison',
  89: 'Yak',
  90: 'Eringer',
  91: 'Evolène',
  92: 'Zebu',
  93: 'Wagyu',
  94: 'Shorthorn',
  95: 'Parthenaise',
  96: 'Rotes Höhenvieh',
  97: 'Valdostana',
  98: 'Zwergzebu',
  99: 'Andere',
}

module.exports = {
  races: races,
}
